server:
  http:
    http_port: 8059
  dns:
    dns_port: 53
    network: udp
    ttl: 3600
storage:
  login: Admin
  password: aadmin
  bucket: testbucket
  hosts:
    - 127.0.0.1:8091
log:
    network_type: udp
    host:
    port: 514
    file path: "./"
    file name: dns_cb.log