title: uhblya
server:
  http:
    port: 8059
  dns:
    port: 53
    network: udp
    ttl: 3600
log:
  network:
  host:
  port: 514
  type: stderr
  debug_mode: false
  severity: LOG_DEBUG
  facility: LOG_LOCAL4
  file_path: "./"
  file_name: logger.log
storage:
  login: Admin
  password: aadmin
  bucket: testbucket
  hosts:
    - 127.0.0.1:8091
