server:
  http:
    http_port: 8059
  dns:
    dns_port: 53
    network: udp
    ttl: 3600
  log:
    network_type: udp
    log_host:
    log_port:
    file_path: "./"
    file_name: dns_cb.log
storage:
  login: Admin
  password: aadmin
  bucket: testbucket
  hosts:
    - 127.0.0.1:8091
