title: uhblya
server:
  http:
    port: 8059
  dns:
    port: 53
    network: udp        # string [udp|tcp]
    ttl: 3600
log:
  network:              # string [udp|tcp]
  host:
  port: 514
  type: stderr          # string [syslog|file]
  debug_mode: false     # bool
  severity: LOG_INFO
  facility: LOG_LOCAL3
  file_path:
  file_name:
storage:
  login: Admin
  password: aadmin
  bucket: testbucket
  hosts:
    - 127.0.0.1:8091
